---
- name: Install docker and docker-compose
  hosts: staging_servers
  become: yes

  tasks:

  - name: Remove old versions of docker
    apt: 
     state: absent
     name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

  - name: Update and install dependencies  
    apt:
     state: present 
     update_cache: yes
     force_apt_get: yes
     name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']

  - name: Install Docker Engine - Community
    apt:
     state: present
     name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
     update_cache: yes
