version: '3'
services:

      front:
        container_name: nginx-proxy
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=127.0.0.1
            - NGINX_PORT=80
        restart: always

      db:
        container_name: mariadb
        image: mariadb:latest
        volumes:
            - mariadb-volume:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
          MYSQL_USER: techadmin
          MYSQL_PASSWORD: techadmin
        ports:
            - "3306:3306"
        restart: always

      back:
        container_name: wordpress
#        image: wordpress:latest
#        run build from Dockerfile
        volumes:
            - wordpress-volume:/var/www/html
              #        ports:
              #            - "8080:80"
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: techadmin
          WORDPRESS_DB_PASSWORD: techadmin
          WORDPRESS_DB_NAME: wordpress
        restart: always

volumes:
   mariadb-volume:
#   nginx-volume:
   wordpress-volume:
