---
- name: Install default apache2 web-server
  hosts: staging_servers
  become: yes


  tasks:
  - name: Install Apache2 Web-server
    apt: name=apache2 state=present


  - name: Start apache and enable on boot
    service: name=apache2 state=started enabled=yes
